paths:
      #? 1. Route for creating comment
      /api/posts:
            post:
                  summary: Create post
                  description: Create a new post.
                  tags:
                        - Post
                  requestBody:
                        required: true
                        content:
                              application/json:
                                    schema:
                                          type: object
                                          properties:
                                                caption:
                                                      type: string
                                                      example: Best Nodejs resources
                                                      required: true
                                                imageUrl:
                                                      type: string
                                                      format: binary
                                                      example: This is one of the best post.
                              multipart/form-data:
                                    schema:
                                          type: object
                                          properties:
                                                caption:
                                                      type: string
                                                      example: Do more be more
                                                      required: true
                                                imageUrl:
                                                      type: string
                                                      format: binary
                                                      example: This is one of the best post.
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 201
                                                      message:
                                                            type: string
                                                            example: Post created successfully.
                                                      data:
                                                            $ref: "#components/schemas/Post"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
      #? 2. Route for update and fetch post
      /api/posts/{postId}:
            put:
                  summary: Update post
                  description: Update existing post.
                  tags:
                        - Post
                  parameters:
                        - name: postId
                          in: path
                          required: true
                          schema:
                                type: string
                  requestBody:
                        required: true
                        content:
                              application/json:
                                    schema:
                                          type: object
                                          properties:
                                                caption:
                                                      type: string
                                                      example: Do more be more
                                                imageUrl:
                                                      type: string
                                                      format: binary
                                                      example: This is one of the best post.
                              multipart/form-data:
                                    schema:
                                          type: object
                                          properties:
                                                caption:
                                                      type: string
                                                      example: Do more be more
                                                imageUrl:
                                                      type: string
                                                      format: binary
                                                      example: This is one of the best post.
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 201
                                                      message:
                                                            type: string
                                                            example: Post created successfully.
                                                      data:
                                                            $ref: "#components/schemas/Post"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>

            #? 3. Route for delete
            delete:
                  summary: Delete post
                  description: Deleting a existing post
                  tags:
                        - Post
                  parameters:
                        - name: postId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Post deleted successfully.
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
            get:
                  summary: Fetch post
                  description: Fetch a post by post id
                  tags:
                        - Post
                  parameters:
                        - name: postId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Post fetched successfully.
                                                      data:
                                                            $ref: "#components/schemas/Post"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
      /api/posts/user/{userId}:
            get:
                  summary: Fetch user's post
                  description: Fetch a specific user's post
                  tags:
                        - Post
                  parameters:
                        - name: userId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: User's post fetched successfully.
                                                      data:
                                                            type: array
                                                            items:
                                                                  $ref: "#components/schemas/Post"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
      /api/posts/all:
            get:
                  summary: Fetch all post
                  description: Fetch all post
                  tags:
                        - Post
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Post list fetched successfully.
                                                      data:
                                                            type: array
                                                            items:
                                                                  $ref: "#components/schemas/Post"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
