paths:
      #? 1. Route for toggle friendship
      /api/friends/toggle-friendship/{friendUserId}:
            post:
                  summary: Create comment on a post
                  description: Add comment to a post.
                  tags:
                        - Friend
                  parameters:
                        - name: friendUserId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        201:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 201
                                                      message:
                                                            type: string
                                                            example: Friend request send successfully.
                                                      data:
                                                            $ref: "#components/schemas/Friend"
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: User removed from friend list successfully.

                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
            #? 3. Route for get pending friend requests
      /api/friends/get-pending-requests:
            get:
                  summary: Fetch pending requests
                  description: Fetch pending friend requests
                  tags:
                        - Friend
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Pending friend requests fetched successfully.
                                                      data:
                                                            type: array
                                                            items:
                                                                  $ref: "#components/schemas/Friend"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>

      #? 2. Route for responding to pending requests
      /api/friends/response-to-request/{friendUserId}:
            post:
                  summary: Update comment
                  description: Update a specific comment by commentId
                  tags:
                        - Friend
                  parameters:
                        - name: friendUserId
                          in: path
                          required: true
                          schema:
                                type: string
                  requestBody:
                        required: true
                        content:
                              application/json:
                                    schema:
                                          type: object
                                          properties:
                                                status:
                                                      type: string
                                                      example: "accepted"
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: You Accept this friend request.
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
            #? 3. Route for get pending friend requests
      /api/friends/get-friends:
            get:
                  summary: Fetch friend list
                  description: Fetch all friends from friend list
                  tags:
                        - Friend
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Friend list fetched successfully.
                                                      data:
                                                            type: array
                                                            items:
                                                                  type: object
                                                                  properties:
                                                                        _id:
                                                                              type: string
                                                                              example: 67ae2cc503577161edc3f8b4

                                                                        name:
                                                                              type: string
                                                                              example: Jane Doe

                                                                        email:
                                                                              type: string
                                                                              example: jane.doe@gmail.com
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
