paths:
      #? 1. Route for creating comment
      /api/comments/{postId}:
            post:
                  summary: Create comment on a post
                  description: Add comment to a post.
                  tags:
                        - Comment
                  parameters:
                        - name: postId
                          in: path
                          required: true
                          schema:
                                type: string
                  requestBody:
                        required: true
                        content:
                              application/json:
                                    schema:
                                          type: object
                                          properties:
                                                message:
                                                      type: string
                                                      example: This is one of the best post.
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: User make a comment on the post.
                                                      data:
                                                            $ref: "#components/schemas/Comment"

                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
            #? 3. Route for reset password
            get:
                  summary: Fetch post's comment
                  description: Fetch all comments of a post
                  tags:
                        - Comment
                  parameters:
                        - name: postId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Comment fetched successfully.
                                                      data:
                                                            type: array
                                                            items:
                                                                  $ref: "#components/schemas/Comment"
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>

      #? 2. Route for updating comment
      /api/comments/{commentId}:
            put:
                  summary: Update comment
                  description: Update a specific comment by commentId
                  tags:
                        - Comment
                  parameters:
                        - name: commentId
                          in: path
                          required: true
                          schema:
                                type: string
                  requestBody:
                        required: true
                        content:
                              application/json:
                                    schema:
                                          type: object
                                          properties:
                                                message:
                                                      type: string
                                                      example: "123456"
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Comment updated successfully by comment owner.
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
            delete:
                  summary: Delete comment
                  description: Delete comment by commentId of a post
                  tags:
                        - Comment
                  parameters:
                        - name: commentId
                          in: path
                          required: true
                          schema:
                                type: string
                  responses:
                        200:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 200
                                                      message:
                                                            type: string
                                                            example: Comment deleted successfully by comment owner.
                        400:
                              content:
                                    application/json:
                                          schema:
                                                type: object
                                                properties:
                                                      statusCode:
                                                            type: number
                                                            example: 400
                                                      message:
                                                            type: string
                                                            example: <Error Message>
